accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup")
]

config/urls.py
from django.contrib import admin
from django.urls import include, path

from django.contrib.auth import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('posts/', include('posts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

pages/urls.py
from django.urls import path
from .views import HomePageView, AboutPageView

urlpatterns = [
    path("", HomePageView.as_view(), name='home'),
    path("about/", AboutPageView.as_view(), name='about'),
]

posts/urls.py
from django.urls import path
from posts import views

urlpatterns = [
    path("", views.PostListView.as_view(), name='list'),
    path("drafts/", views.DraftPostListView.as_view(), name='drafts'),
    path("archived/", views.ArchivedPostListView.as_view(), name='archived'),
    path("new/", views.PostCreateView.as_view(), name='new'),
    path("<int:pk>/", views.PostDetailView.as_view(), name='detail'),
    path("<int:pk>/edit/", views.PostUpdateView.as_view(), name='edit'),
    path("<int:pk>/delete/", views.PostDeleteView.as_view(), name='delete'),
    path("edit/status/<int:pk>", views.PostUpdateToDraftView.as_view(), name='update_to_draft'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Role(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=256)

    def __str__(self):
        return self.name
    
class Team(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=256)

    def __str__(self):
        return self.name

class CustomUser(AbstractUser):
    role = models.ForeignKey(
        Role,
        on_delete=models.CASCADE,
        blank=True, null=True
    )
    team = models.ForeignKey(
        Team,
        on_delete=models.CASCADE,
        blank=True, null=True
    )

pages/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model

class Status(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=256)

    def __str__(self):
        return self.name
    
class Post(models.Model):
    title = models.CharField(max_length=128)
    subtitle = models.CharField(max_length=256)
    author = models.ForeignKey(
        get_user_model(),
        on_delete = models.CASCADE
    )
    status = models.ForeignKey(
        Status,
        on_delete = models.CASCADE
    )
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("detail", args=[self.id])

accounts/forms.py
from django.contrib.auth.forms import (
    UserChangeForm,
    UserCreationForm
)
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ("email",)
        # fields = UserCreationForm.Meta.fields + ("email", "role", "team")
    
class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm):
        model = CustomUser
        fields = UserChangeForm.Meta.fields

accounts/views.py
from django.views.generic import CreateView
# from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from .forms import CustomUserCreationForm

class SignUpView(CreateView):
    template_name = "registration/signup.html"
    # form_class = UserCreationForm
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")

pages/views.py
from django.views.generic import TemplateView

class HomePageView(TemplateView):
    template_name = "pages/home.html"

class AboutPageView(TemplateView):
    template_name = "pages/about.html"

posts/views.py
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    DeleteView,
    UpdateView
)
from django.contrib.auth.mixins import(
    LoginRequiredMixin,
    UserPassesTestMixin
)
from django.urls import reverse_lazy
from .models import Post, Status


class PostListView(ListView):
    template_name = 'posts/list.html'
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pub_status = Status.objects.get(name="published")
        context["post_list"] = (
            Post.objects
            .filter(status=pub_status)
            .order_by("created_on").reverse()
        )
        return context
    
class DraftPostListView(LoginRequiredMixin, ListView):
    template_name = "posts/list.html"
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        draft_status = Status.objects.get(name="draft")
        context["post_list"] = (
            Post.objects
            .filter(status=draft_status)
            .filter(author=self.request.user)
            .order_by("created_on").reverse()
        )
        return context
    
class ArchivedPostListView(LoginRequiredMixin, ListView):
    template_name = "posts/list.html"
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        arch_status = Status.objects.get(name="archived")
        context["post_list"] = (
            Post.objects
            .filter(status=arch_status)
            .order_by("created_on").reverse()
        )
        return context

class PostDetailView(DetailView): 
    template_name = 'posts/detail.html'
    model = Post

class PostCreateView(LoginRequiredMixin, CreateView):
    template_name = 'posts/new.html'
    model = Post
    fields = ['title', 'subtitle', 'body', 'status']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    template_name = "posts/delete.html"
    model = Post
    success_url = reverse_lazy("list")

    def test_func(self):
        post = self.get_object()
        return post.author == self.request.user

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    template_name = "posts/edit.html"
    model = Post
    fields = ['title', 'subtitle', 'body', 'status']

    def test_func(self):
        post = self.get_object()
        return post.author == self.request.user

class PostUpdateToDraftView(UpdateView):
    template_name = "posts/update_status.html"
    model = Post
    fields = ['status']

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://kit.fontawesome.com/b8ce32ba45.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body class="main">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">My Blog</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                    <a class="nav-link" href="{% url 'about' %}">About</a>
                    <a class="nav-link" href="{% url 'list' %}">Posts</a>
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'drafts' %}">Drafts</a>
                    <a class="nav-link" href="{% url 'archived' %}">Archived</a>
                    <a class="nav-link" href="{% url 'new' %}">New Post</a>
                    <a class="nav-link" href="{% url 'password_change' %}">Change password</a>
                    <form method="POST" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <input type="submit" class="nav-link" value="Log Out">
                    </form>
                    {% else %}
                    <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    
    <div class="container">
        {% block content %}{% endblock content %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

</body>
</html>

templates/pages/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{% endblock title %}

{% block content %}
<div class="about-container">
    <div class="about-image">
    </div>
    <div class="about-content">
        <h1>About Me</h1>
        <h2>Lorem Ipsum Dolor</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vitae arcu sit amet lorem faucibus hendrerit. Donec et quam eu orci cursus euismod. Nam vel tortor justo. In eu turpis at eros vestibulum tincidunt. Aliquam erat volutpat. Sed at risus vel orci varius congue. Curabitur et tortor eget nisl dapibus ultrices. Sed malesuada tellus ac turpis vestibulum, a eleifend enim malesuada.</p>
        <p>Morbi quis ante nec risus tincidunt volutpat. Cras tristique nulla non ipsum convallis, eget venenatis arcu aliquet. Donec fringilla purus vitae arcu fermentum, in finibus felis fermentum. Phasellus scelerisque dolor nec ex vehicula, sit amet maximus mi convallis. Nulla nec nunc ac eros dictum sollicitudin nec non lorem. Ut nec magna at lorem gravida aliquet vel et ligula.</p>
    </div>
</div>
{% endblock content %}

templates/pages/home.html
{% extends 'base.html' %}

{% block title %}{% endblock title %}

{% block content %}
<header class="main-header">
    <div class="hero-section">
        <div class="hero-content">
            <h2>Welcome</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sed diam vel neque vehicula vulputate.</p>
            <a href="#about" class="cta-button">More info</a>
        </div>
    </div>
</header>

{% endblock content %}

templates/posts/delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Post</h1>
<h3>Are you sure you want to delete {{ post.title }}? </h3>
<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'list' %}" class="btn btn-secondary">Cancel</a>
    <!-- <a href="{% url 'detail' object.pk %}" class="btn btn-secondary">Cancel</a> -->
</form>

{% endblock content %}

templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}{{ post.title }}{% endblock title %}

{% block content %}

<h1>{{ post.title }}</h1>
<h3>{{ post.subtitle }}</h3>
<small>Created on: {{ post.created_on }}</small>
<p>{{ post.body }}</p>
<br>
<a href="{% url 'list' %}" class="btn btn-secondary">Go back</a>

{% if user.is_authenticated %}
{% if user == post.author %}
<a href="{% url 'delete' post.id%}" class="btn btn-danger"><i class="fa-solid fa-trash"></i></a>
<!-- <a href="{% url 'edit' post.id%}" class="btn btn-sm btn-warning"><i class="fa-solid fa-pen-to-square"></i></a> -->
{% endif %}
{% endif %}

{% endblock content %}

templates/posts/edit.html
{% extends 'base.html' %}

{% block title %}{{ post.title }}{% endblock title %}

{% block content %}
<h2>Edit Post</h2>
<form method="post" class="m-2">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-success" value="Save changes">
</form>
<a href="{% url 'list' %}" class="btn btn-secondary">Cancel</a>
<!-- <a href="{% url 'detail' object.pk %}" class="btn btn-secondary">Cancel</a> -->
{% endblock %}

templates/posts/list.html
{% extends 'base.html' %}

{% block title %}Posts{% endblock title %}

{% block content %}
<h1>Posts</h1>
{% for post in post_list %}
<div class="post-section">
    <div class="card-body post">
        <h5 class="card-title">{{ post.title }}</h5>
        <h6 class="card-subtitle mb-2 text-body-secondary">{{ post.subtitle }}</h6>
        <p class="card-text">{{ post.body|truncatechars:64 }}</p>
        <a href="{% url 'detail' post.id %}" class="btn btn-sm btn-dark m-1">Continue reading...</a>
        <a href="{% url 'edit' post.id%}" class="btn btn-sm btn-warning"><i class="fa-solid fa-pen-to-square"></i></a>
        {% if user.is_authenticated %}
            {% if user == post.author %}
                <form method="POST" action="{% url 'update_to_draft' post.id %}">
                    {% csrf_token %}
                    <input type="hidden" id="id_status" name="status" value="2">
                    <input type="submit" class="card_link" value="Draft">
                </form>
                {% endif %}
        {% endif %}
    </div>
</div>
<br/>
{% endfor %}
{% endblock content %}

templates/posts/new.html
{% extends 'base.html' %}

{% block title %}New Post{% endblock title %}

{% block content %}

<h1>New Post</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-success" value="Create">
</form>

{% endblock content %}